### ISSUE TITLE
Use GADTs to ensure Transformation correctness during compilation time

### ISSUE THREAD

**Issue by radrow** [mkfilipiuk/JPP_haskell_1#5]
The type `Transform` may have invalid values, for instance `TransformList [RotationTransform 1, RotationTransform 1]`. In your solution you should forbid this case. One possible option to solve it would be to define `Transform` in GADT terms:

```haskell
{-# LANGUAGE GADTs #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE KindSignatures #-}

data TransformType = Rot | Tran
data Transform (r :: TransformType) where
  NilR :: Transform Rot
  NilT :: Transform Tran
  Rotation :: R -> Transform Tran -> Transform R
  Translation :: Vec -> Transform Rot -> Transform Tran 
```

After that you may use `ExistentialQuantification` to escape `Type` constraints as in this thread: https://stackoverflow.com/questions/53904818/weaken-gadts-type-constraints-to-deal-with-unpredictable-data

**Comment by mkfilipiuk** [comment]
Sounds really cool! Unfortunately due to very short deadline, I won't be able to implement it
